# Generated by Django 4.2.30 on 2026-10-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_cancellation_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
