"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================
# SECURITY
# =============================================

# ⚠️ Generate a new secret key for production:
# python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = 'django-insecure-ahw@(v2zyav9rjx$yqhgjer+qfa$xiv7k1d37!q$0w8ylwba3k'

# ⚠️ Set to False in production
DEBUG = True

# ⚠️ Restrict to your actual domains in production
ALLOWED_HOSTS = [
    '*',                      # ⚠️ Remove this in production!
    '192.168.100.74',
    '127.0.0.1',
    'localhost',
    'www.delightcareplus.com',
]


# =============================================
# APPLICATIONS
# =============================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig',
]


# =============================================
# MIDDLEWARE
# =============================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =============================================
# URLS & TEMPLATES
# =============================================

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# =============================================
# DATABASE
# =============================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =============================================
# PASSWORD VALIDATION
# =============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================
# INTERNATIONALIZATION
# =============================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'   # ⭐ Changed from UTC to Kenya time
USE_I18N = True
USE_TZ = True


# =============================================
# STATIC & MEDIA FILES
# =============================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "store" / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================
# DEFAULT AUTO FIELD
# =============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================
# M-PESA CONFIGURATION — PRODUCTION
# =============================================

# Production Credentials (from Safaricom developer portal)
# ⚠️ REPLACE THESE with your actual Production values!
MPESA_CONSUMER_KEY = 'yKjRtGlHpISwYuLq4f9OBVImkmAmEOP69RFjqA8pqjPMKo93'
MPESA_CONSUMER_SECRET = 'lGeHAzeNSuzfCuTtoQWiUkTBQ1Z22Se7qEsodV6NLfah4UCgJT8g7vSeDN0Anvek'

# Your real shortcode and passkey
MPESA_SHORTCODE = '4701129'
MPESA_PASSKEY = '1d2873038e18958d0b4fbe4693a56798c5d1a4fe6a3419612094409e48c38a42'

# Environment
MPESA_ENVIRONMENT = 'production'

# Base URLs
if MPESA_ENVIRONMENT == 'production':
    MPESA_BASE_URL = 'https://api.safaricom.co.ke'
else:
    MPESA_BASE_URL = 'https://sandbox.safaricom.co.ke'

# Callback URL — must be HTTPS and publicly accessible
# ⚠️ CHANGE this to your actual live domain
MPESA_CALLBACK_URL = 'https://delightcareplus.com/mpesa/callback/'


# =============================================
# LOGGING — For M-Pesa debugging
# =============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'mpesa_debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'store': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# =============================================
# SECURITY SETTINGS FOR PRODUCTION
# =============================================
# Uncomment these AFTER your site is fully HTTPS

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True